export type ProviderField = {
  key: string;
  label: string;
  secret?: boolean;
  required?: boolean;
  control?: "text" | "password" | "url" | "email" | "number" | "checkbox" | "options" | "color";
  placeholder?: string;
  help?: string;
  default?: string;
  options?: { value: string; label: string }[];
};

export type Provider = {
  id: string;
  name: string;
  fields: ProviderField[];
  delivery_kind?: string;
  implementation_note?: string;
};

export type FieldSection = "destination" | "auth" | "options" | "advanced";

const destinationKeys = new Set([
  "url",
  "webhook_url",
  "endpoint",
  "server",
  "site",
  "host",
  "domain",
  "to",
  "from",
  "chat_id",
  "channel",
  "room",
  "topic",
  "service",
  "device",
  "user",
  "user_id",
]);

const authKeys = new Set([
  "authorization",
  "token",
  "bot_token",
  "api_key",
  "webhook_key",
  "password",
  "secret",
  "access_token",
  "client_secret",
  "username",
]);

export function enhanceProviderField(field: ProviderField, providerID: string): ProviderField {
  const key = field.key.toLowerCase();
  const next: ProviderField = { ...field };

  if ((providerID === "webhook" || providerID.startsWith("custom_") || key.includes("webhook")) && key === "url") {
    next.label = "Webhook URL";
  }
  if (key === "webhook_url") next.label = next.label || "Webhook URL";
  if (key === "authorization") next.label = "Authorization header";
  if (key === "server") next.label = next.label === "Server" ? "Server URL" : next.label;
  if (key === "host") next.label = next.label === "Host" ? "SMTP host" : next.label;
  if (key === "to") next.label = next.label === "To" ? "Recipients" : next.label;

  if (!next.control && isURLField(key)) next.control = "url";
  if (next.secret) next.control = next.control || "password";

  if (!next.placeholder) {
    if (isURLField(key)) next.placeholder = providerID === "webhook" ? "https://example.com/webhook" : "https://...";
    if (key === "authorization") next.placeholder = "Bearer ...";
    if (key === "server") next.placeholder = "https://server.example.com";
    if (key === "port") next.placeholder = "587";
    if (key === "from") next.placeholder = "Silo <notifications@example.com>";
    if (key === "to") next.placeholder = "admin@example.com";
  }

  if (!next.help) {
    if (providerID === "webhook" && key === "url") next.help = "Silo will POST notification JSON to this URL.";
    if (key === "authorization") next.help = "Optional value sent as the Authorization header.";
    if (key === "webhook_url") next.help = "Paste the incoming webhook URL generated by the destination service.";
    if (key === "to") next.help = "Use Silo users below when available, or enter comma-separated recipients.";
  }

  return next;
}

export function fieldSection(field: ProviderField, providerID: string): FieldSection {
  const key = field.key.toLowerCase();
  if (destinationKeys.has(key) || isURLField(key) || key.endsWith("_id")) return "destination";
  if (key === "username" && !authUsernameProviders.has(providerID)) return "options";
  if (field.secret || authKeys.has(key) || key.includes("token") || key.includes("secret") || key.includes("key")) return "auth";
  if (field.control === "checkbox" || field.control === "options" || ["priority", "color", "event", "visibility", "tls_mode"].includes(key)) return "options";
  if (providerID === "smtp" && ["port"].includes(key)) return "destination";
  return "advanced";
}

export function providerHelpText(provider?: Provider): string {
  if (!provider) return "Choose a provider, then fill in the destination and credentials it needs.";
  if (provider.implementation_note) return provider.implementation_note;
  if (provider.delivery_kind === "bridge") return "Requires an external bridge service configured by the operator.";
  return "Implemented directly by this plugin.";
}

export function isURLField(key: string) {
  return key === "url" || key === "webhook_url" || key === "endpoint" || key === "server" || key.endsWith("_url");
}

const authUsernameProviders = new Set([
  "smtp",
  "smtp2go",
  "office365",
  "mqtt",
  "rsyslog",
  "syslog",
]);
